# Model
model: SASRec #

# Dataset
dataset: amazon-electronics

# Data loading and splitting
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, rating, timestamp] 
eval_setting: TO_LS,full 

# Training settings
epochs: 2
train_batch_size: 2048
eval_batch_size: 2048
learning_rate: 0.001
stopping_step: 10
train_neg_sample_args: ~


# Evaluation settings
metrics: [Recall, NDCG, MRR, ItemCoverage]
topk: [10]
valid_metric: NDCG@10 

# Other settings
checkpoint_dir: saved_baselines/ # Directory to save model checkpoints
show_progress: True
seed: 2025 # For reproducibility
accelerator: 'gpu' 
device_id: 0 #if you have gpu