#! /bin/bash
#SBATCH --job-name=infer_recbole
#SBATCH --output=job_output/infer_recformer_%A_%a.out
#SBATCH --ntasks=1
#SBATCH --time=00:15:00 
#SBATCH --partition=gpu_a100
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8 
#SBATCH --gpus=1


source recformer_env/bin/activate 


echo "Starting inference using config: recbole_inference_config.yaml"
python run.py --config_file recbole_inference_config.yaml
echo "Inference job finished"