data_path: 'downstream/'
dataset: Instruments #Instruments, Scientific, Arts, Office, Games, Pet
benchmark_filename: [train, valid, test]
alias_of_item_id: [item_id_list]
load_col:
  inter: [user_id, item_id_list, item_id]
  item: [item_id, categories]
train_neg_sample_args: ~
unisrec_transform: ~

topk: [10, 50]
metrics: [HIT, Recall, NDCG, MRR]
valid_metric: NDCG@10
eval_batch_size: 2048
stopping_step: 10