model: SASRec
dataset: MIND
data_path: ./recbole_data/

PAD_TOKEN: "[PAD]" 
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, timestamp]
    item: [item_id, title, categories, brand] 

# SASRec specific parameters
n_layers: 2
n_heads: 1
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'

# Training Settings
epochs: 50
train_batch_size: 512  
eval_batch_size: 512
learning_rate: 0.001
stopping_step: 10
train_neg_sample_args: ~ 

# Lenient filtering for news recommendation
min_user_inter_num: 2
min_item_inter_num: 1
filter_inter_by_user_or_item: False

metrics: [Recall, NDCG, MRR]
topk: [10, 20]
valid_metric: NDCG@10 

eval_args:
    group_by: user
    order: TO      
    mode: full     
    split: {'RS': [0.8, 0.1, 0.1]}

# Checkpoint Settings
checkpoint_dir: ./saved_baselines/mind_sasrec/
show_progress: True
seed: 2025
reproducibility: True
gpu_id: '0,1,2,3' 
use_gpu: True 